# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: e.Ray
  de: e.Ray
  en: e.Ray
email: your-email@domain.com
description:
  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  de: Wir sind tolle studenten die awesome shit producen...
  es: hollla
index:
  en:
  de: index_de.html
  es: index_es.html
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "/eray.io" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: sakulstra
github_username:  sakulstra

# Build settings
markdown: kramdown

include: ['_pages']

compress_html:
  clippings: all
  comments:  all
  endings:   all
  profile:  false

sass:
  style: compressed